resources:
  repositories:
  - repository: templates
    type: git
    name: DevOps/Amrock.DevOps.Pipelines.Templates.Cloud
    ref: refs/tags/stable

trigger:
  branches:
    include:
      - develop

stages:
#compile
- template: stages/nodejs-compile.yaml@templates
  parameters:
    stageName: sizing_tool
    projectPath: /
    sonarProjectName: SizingTool
    snykOrganization: appraisal
    #publishPath: /dist

#deploy
- template: stages/nodejs-deploy.yaml@templates
  parameters:
    environments:
    - stageName: sizingtool_test
      environment: test
      dependsOn: nodejs_compile_sizing_tool
      poolName: Amrock_Shared_NonProd_AWS_ADO_Runner
      bucketName: tap-refinement-sizing-tool
      cloudFrontDistributionId: E3VAIXS4HLEC10
	    sourceFilePath: 'app/Refinement-Sizing-Tool'
      variables: pipelines/variables/test.yaml@self
	    replaceTokens: 'app/*/*.js'