resources:
  repositories:
  - repository: templates
    type: git
    name: DevOps/Amrock.DevOps.Pipelines.Templates.Cloud
    ref: refs/tags/alpha

trigger:
  branches:
    include:
      - develop

stages:
#compile
- template: stages/nodejs-compile.yaml@templates
  parameters:
    stageName: refinement_sizing_tool
    projectPath: /
    sonarProjectName: RefinementSizingTool
    snykOrganization: title-and-tax
    #publishPath: /dist

#deploy
- template: stages/nodejs-deploy.yaml@templates
  parameters:
    environments:
    - stageName: refinementsizingtool_test
      environment: test
      dependsOn: nodejs_compile_refinement_sizing_tool
      poolName: Amrock_Shared_Sandbox_AWS_ADO_Runner
      variables: pipelines/variables/test.yaml@self
      bucketName: tap-refinement-sizing-tool
      cloudFrontDistributionId: E3VAIXS4HLEC10
	    sourceFilePath: 'app/Refinement-Sizing-Tool'
	    replaceTokens: 'app/*/*.js'