resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/Amrock.DevOps.Pipelines.Templates.Cloud
      ref: refs/tags/stable

trigger: none

stages:
#compile
- template: stages/nodejs-compile.yaml@templates
  parameters:
    stageName: sizing_tool
    projectPath: /
    sonarProjectName: SizingTool
    snykOrganization: shared-1c5
    sonarArgument:
      sonar.coverage.exclusions="**/*.ts"