resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/Amrock.DevOps.Pipelines.Templates.Cloud
      ref: refs/tags/stable

trigger: none

stages:
  #compile
  - template: stages/nodejs-compile.yaml@templates
    parameters:
      stageName: refinement_sizing_tool
      projectPath: /
      sonarProjectName: RefinementSizingTool
      snykOrganization: title-and-tax

  #deploy-test
  - template: stages/nodejs-deploy.yaml@templates
    parameters:
      environments:
        - stageName: refinementsizingtool_staging
          environment: staging
          dependsOn: nodejs_compile_refinement_sizing_tool
          poolName: Amrock_Shared_NonProd_AWS_ADO_Runner
          bucketName: refinementsizingtool-staging.amrock-sb.foc.zone
          cloudFrontDistributionId: $(StagingCloudFrontId)
          sourceFilePath: "app/refinementsizingtool"
          variables: pipelines/variables/staging.yaml@self
          replaceTokens: "app/*/*.js"
        - stageName: refinementsizingtool_prod
          environment: prod
          dependsOn: nodejs_deploy_refinementsizingtool_staging
          poolName: Amrock_Shared_Prod_AWS_ADO_Runner
          bucketName: refinementsizingtool.amrock-sb.foc.zone
          cloudFrontDistributionId: $(ProdCloudFrontId)
          sourceFilePath: "app/RefinementSizingTool"
          variables: pipelines/variables/prod.yaml@self
          replaceTokens: "app/*/*.js"
